# app/config/antizapret_params.py

ANTIZAPRET_PARAMS = [
    {
        "key": "route_all",
        "env": "ROUTE_ALL",
        "type": "flag",
        "default": "n",
        "html_id": "route-all-toggle",
        "title": "Всех доменов, кроме .ru",
        "description": "Перенаправляет весь трафик через antizapret, кроме российских доменов (.ru, .рф) и исключений из exclude-hosts.txt",
    },
    {
        "key": "discord_include",
        "env": "DISCORD_INCLUDE",
        "type": "flag",
        "default": "n",
        "html_id": "discord-toggle",
        "title": "Discord",
        "description": "Перенаправляет трафик Discord через antizapret, включая голосовые каналы и обмен сообщениями",
    },
    {
        "key": "cloudflare_include",
        "env": "CLOUDFLARE_INCLUDE",
        "type": "flag",
        "default": "n",
        "html_id": "cloudflare-toggle",
        "title": "Cloudflare",
        "description": "Перенаправляет трафик Cloudflare через antizapret, включая сайты и сервисы, использующие Cloudflare для защиты от DDoS-атак",
    },
    {
        "key": "telegram_include",
        "env": "TELEGRAM_INCLUDE",
        "type": "flag",
        "default": "n",
        "html_id": "telegram-toggle",
        "title": "Telegram",
        "description": "Перенаправляет трафик Telegram через Antizapret, включая обмен сообщениями, каналы и группы",
    },
    {
        "key": "block_ads",
        "env": "BLOCK_ADS",
        "type": "flag",
        "default": "n",
        "html_id": "AdBlock-toggle",
        "title": "AdBlock",
        "description": "Блокировка рекламы, трекеров, вредоносных программ и фишинговых веб-сайтов в AntiZapret VPN (Antizapret-*) на основе правил AdGuard и OISD",
    },
    {
        "key": "whatsapp_include",
        "env": "WHATSAPP_INCLUDE",
        "type": "flag",
        "default": "n",
        "html_id": "whatsapp-toggle",
        "title": "WhatsApp",
        "description": "Перенаправляет трафик WhatsApp через Antizapret, включая обмен сообщениями, звонки и медиафайлы.",
    },
    {
        "key": "roblox_include",
        "env": "ROBLOX_INCLUDE",
        "type": "flag",
        "default": "n",
        "html_id": "roblox-toggle",
        "title": "Roblox",
        "description": "Перенаправляет трафик Roblox через Antizapret, включая игровой контент, платежи и социальные функции.",
    },
    {
        "key": "OPENVPN_BACKUP_TCP",
        "env": "OPENVPN_BACKUP_TCP",
        "type": "flag",
        "default": "n",
        "html_id": "OPENVPN_BACKUP_TCP-toggle",
        "title": "TCP",
        "description": "Включает резервные порты OpenVPN TCP (80,443,504,508) для обхода блокировок провайдеров, если стандартный порт заблокирован.",
    },
    {
        "key": "OPENVPN_BACKUP_UDP",
        "env": "OPENVPN_BACKUP_UDP",
        "type": "flag",
        "default": "n",
        "html_id": "OPENVPN_BACKUP_UDP-toggle",
        "title": "UDP",
        "description": "Включает резервные порты OpenVPN UDP (80,443,504,508) для обхода блокировок провайдеров, если стандартный порт заблокирован.",
    },
    {
        "key": "WIREGUARD_BACKUP",
        "env": "WIREGUARD_BACKUP",
        "param_label": "WIREGUARD_BACKUP_TCP",
        "type": "flag",
        "default": "n",
        "html_id": "WIREGUARD_540_580-toggle",
        "title": "WireGuard/AmneziaWG",
        "description": "Включает резервные порты WireGuard/AmneziaWG (540,580) для обхода блокировок провайдеров, если стандартный порт заблокирован.",
    },
    {
        "key": "ANTIZAPRET_WARP",
        "env": "ANTIZAPRET_WARP",
        "type": "flag",
        "default": "n",
        "html_id": "ANTIZAPRET_WARP-toggle",
        "title": "Cloudflare WARP for Antizapret",
        "description": "Включает отправку трафика Antizapret через Cloudflare WARP для улучшения устойчивости к блокировкам",
    },
    {
        "key": "VPN_WARP",
        "env": "VPN_WARP",
        "type": "flag",
        "default": "n",
        "html_id": "VPN_WARP-toggle",
        "title": "Cloudflare WARP for VPN outbound",
        "description": "Включает отправку исходящего VPN трафика через Cloudflare WARP",
    },
    {
        "key": "ssh_protection",
        "env": "SSH_PROTECTION",
        "type": "flag",
        "default": "n",
        "html_id": "ssh_protection-toggle",
        "title": "Защита от брутфорса SSH",
        "description": "Включить защиту от перебора паролей SSH (не более 3 новых подключений в час с одного IP)",
    },
    {
        "key": "attack_protection",
        "env": "ATTACK_PROTECTION",
        "type": "flag",
        "default": "n",
        "html_id": "attack_protection-toggle",
        "title": "Защита от атак",
        "description": "Блокирует подозрительную сетевую активность: превышение лимита подключений и попытки подключения по нетипичным портам.",
    },
    {
        "key": "scan_protection",
        "env": "SCAN_PROTECTION",
        "type": "flag",
        "default": "n",
        "html_id": "scan_protection-toggle",
        "title": "Scan protection",
        "description": "Скрывает сервер от простого сканирования: отключает ответ на ping и на запросы к закрытым портам.",
    },
    {
        "key": "torrent_guard",
        "env": "TORRENT_GUARD",
        "type": "flag",
        "default": "n",
        "html_id": "torrent_guard-toggle",
        "title": "Torrent Guard",
        "description": "Torrent Guard — если хостер запрещает торренты или присылает жалобы, эта опция поможет: при обнаружении торрент-трафика VPN будет блокироваться на 1 минуту",
    },
    {
        "key": "restrict_forward",
        "env": "RESTRICT_FORWARD",
        "param_label": "restrict_forward",
        "type": "flag",
        "default": "n",
        "html_id": "restrict_forward-toggle",
        "title": "Ограничение форвардинга",
        "description": "Включить ограничение форвардинга — через AntiZapret VPN будет маршрутизироваться только трафик к IP-адресам, которые явно указаны в файлах config/forward-ips.txt и result/route-ips.txt",
    },
    {
        "key": "clear_hosts",
        "env": "CLEAR_HOSTS",
        "type": "flag",
        "default": "n",
        "html_id": "clear-hosts-toggle",
        "title": "Очистка хостов: казино-домены",
        "description": "Удаляет домены с азартными играми при авто-обновлении списков (≈ 170 000 записей), уменьшая объём мусора и нагрузку.",
    },
    {"key": "openvpn_host",           "env": "OPENVPN_HOST",           "type": "string", "default": "", "html_id": "openvpn-host-input"},
    {"key": "wireguard_host",         "env": "WIREGUARD_HOST",         "type": "string", "default": "", "html_id": "wireguard-host-input"},
]

# Список разрешенных IP-файлов с отображаемыми именами, описаниями и метаданными AS
IP_FILES = {
    "akamai-ips.txt": {
        "name": "Akamai",
        "description": "Маршрутизация сетей Akamai через Antizapret (CDN и edge-сервисы).",
        "as_numbers": ["AS20940", "AS16625", "AS35993"],
        "category": "cdn",
        "what_hosts": "CDN: Apple App Store, Adobe, крупные новостные сайты, стриминг-платформы. Один из крупнейших мировых CDN-провайдеров.",
        "tags": ["cdn", "streaming", "enterprise"],
    },
    "amazon-ips.txt": {
        "name": "Amazon",
        "description": "Маршрутизация сетей Amazon/AWS через Antizapret.",
        "as_numbers": ["AS16509", "AS14618", "AS8987", "AS9059", "AS38895", "AS45773", "AS39111"],
        "category": "cloud",
        "what_hosts": "AWS: Twitch, Slack, GitHub Actions, Netflix (частично), Amazon.com, Discord (голосовые серверы), сотни тысяч SaaS-сервисов и игровых серверов.",
        "tags": ["cloud", "gaming", "social", "streaming", "enterprise"],
    },
    "digitalocean-ips.txt": {
        "name": "DigitalOcean",
        "description": "Маршрутизация сетей DigitalOcean через Antizapret.",
        "as_numbers": ["AS14061", "AS46652", "AS200130"],
        "category": "hosting",
        "what_hosts": "Хостинг независимых разработчиков и стартапов, игровые серверы сообщества, self-hosted сервисы.",
        "tags": ["hosting", "gaming"],
    },
    "google-ips.txt": {
        "name": "Google",
        "description": "Маршрутизация сетей Google/Google Cloud через Antizapret.",
        "as_numbers": ["AS15169"],
        "category": "cloud",
        "what_hosts": "YouTube, Google Search, Gmail, Google Play, Android обновления, Google Maps, Google Drive, Firebase, Google Cloud Platform.",
        "tags": ["cloud", "streaming", "enterprise", "mobile"],
    },
    "hetzner-ips.txt": {
        "name": "Hetzner",
        "description": "Маршрутизация сетей Hetzner через Antizapret.",
        "as_numbers": ["AS24940", "AS213230", "AS212317", "AS215859", "AS210248"],
        "category": "hosting",
        "what_hosts": "Немецкий хостинг-провайдер: игровые серверы, self-hosted приложения, европейские разработчики.",
        "tags": ["hosting", "gaming", "europe"],
    },
    "ovh-ips.txt": {
        "name": "OVH",
        "description": "Маршрутизация сетей OVH через Antizapret.",
        "as_numbers": ["AS16276", "AS35540"],
        "category": "hosting",
        "what_hosts": "Французский хостинг: европейские игровые серверы (MMO, Minecraft), хостинг игровых проектов, VPS-серверы.",
        "tags": ["hosting", "gaming", "europe"],
    },
    "cloudflare-ips.txt": {
        "name": "Cloudflare",
        "description": "Маршрутизация сетей Cloudflare через Antizapret.",
        "as_numbers": ["AS13335", "AS209242"],
        "category": "cdn",
        "what_hosts": "Cloudflare CDN/Proxy: сайты и API за Cloudflare, защитные страницы, edge-сервисы.",
        "tags": ["cdn", "security", "enterprise"],
    },
    "fastly-ips.txt": {
        "name": "Fastly",
        "description": "Маршрутизация сетей Fastly через Antizapret.",
        "as_numbers": ["AS54113"],
        "category": "cdn",
        "what_hosts": "CDN: Reddit, GitHub, Twitter/X, Spotify, Vimeo, The Guardian, BBC. Ускорение контента для крупных медиа-платформ.",
        "tags": ["cdn", "social", "streaming", "enterprise"],
    },
    "azure-ips.txt": {
        "name": "Microsoft Azure",
        "description": "Маршрутизация сетей Microsoft/Azure через Antizapret.",
        "as_numbers": ["AS8075"],
        "category": "cloud",
        "what_hosts": "Microsoft Azure, Xbox Live, LinkedIn, GitHub (частично), Microsoft 365, Teams, OneDrive, Windows Update.",
        "tags": ["cloud", "gaming", "social", "enterprise"],
    },
    "oracle-ips.txt": {
        "name": "Oracle",
        "description": "Маршрутизация сетей Oracle Cloud через Antizapret.",
        "as_numbers": ["AS31898", "AS54253", "AS1219", "AS6142", "AS14544", "AS20054"],
        "category": "cloud",
        "what_hosts": "Oracle Cloud Infrastructure: бесплатный tier популярен для self-hosted проектов, TikTok (частично использует OCI).",
        "tags": ["cloud", "hosting"],
    },
    "cdn77-ips.txt": {
        "name": "CDN77",
        "description": "Маршрутизация сетей CDN77 через Antizapret.",
        "as_numbers": ["AS60068", "AS212238"],
        "category": "cdn",
        "what_hosts": "CDN для стриминга и медиа-контента. Используется многими стриминг-сервисами.",
        "tags": ["cdn", "streaming"],
    },
    "m247-ips.txt": {
        "name": "M247",
        "description": "Маршрутизация сетей M247 через Antizapret.",
        "as_numbers": ["AS9009"],
        "category": "hosting",
        "what_hosts": "M247 Europe SRL: транзит и дата-центры, часто используется CDN/hosting-сервисами.",
        "tags": ["hosting", "transit", "europe"],
    },
}

# Встроенные пресеты выбора провайдеров для маршрутизации
# Хранятся в БД и могут быть изменены пользователем; при первом запуске засеиваются из этого списка.
BUILTIN_CIDR_PRESETS = [
    {
        "key": "cdn_only",
        "name": "Только CDN",
        "description": "Akamai, Fastly, CDN77, Cloudflare — крупнейшие CDN. Охватывает большинство заблокированных сайтов с минимальным количеством маршрутов.",
        "sort_order": 10,
        "providers": [
            "akamai-ips.txt",
            "fastly-ips.txt",
            "cdn77-ips.txt",
            "cloudflare-ips.txt",
        ],
        "settings": {
            "region_scopes": ["all"],
            "exclude_ru_cidrs": False,
            "include_non_geo_fallback": True,
        },
    },
    {
        "key": "web_surfing",
        "name": "Веб-серфинг",
        "description": "Оптимально для обычного веб-серфинга: Google (поиск, YouTube), Fastly (Reddit, GitHub, Twitter/X, Spotify), Akamai (крупные СМИ, Adobe). Баланс покрытия и объёма маршрутов.",
        "sort_order": 15,
        "providers": [
            "google-ips.txt",
            "fastly-ips.txt",
            "akamai-ips.txt",
        ],
        "settings": {
            "region_scopes": ["all"],
            "exclude_ru_cidrs": False,
            "include_non_geo_fallback": True,
        },
    },
    {
        "key": "social_media",
        "name": "Соцсети и мессенджеры",
        "description": "Twitter/X (Fastly), Instagram (Amazon), Twitch (AWS). Оптимально для общения и социальных сетей.",
        "sort_order": 20,
        "providers": [
            "amazon-ips.txt",
            "fastly-ips.txt",
        ],
        "settings": {
            "region_scopes": ["all"],
            "exclude_ru_cidrs": False,
            "include_non_geo_fallback": True,
        },
    },
    {
        "key": "streaming",
        "name": "Видео и стриминг",
        "description": "YouTube (Google), Twitch (AWS), Netflix CDN (Akamai/Fastly), Spotify (Fastly), Vimeo (Fastly). Для любителей видеоконтента.",
        "sort_order": 30,
        "providers": [
            "google-ips.txt",
            "amazon-ips.txt",
            "akamai-ips.txt",
            "fastly-ips.txt",
        ],
        "settings": {
            "region_scopes": ["all"],
            "exclude_ru_cidrs": False,
            "include_non_geo_fallback": True,
        },
    },
    {
        "key": "gaming",
        "name": "Игровые сервисы",
        "description": "AWS (Riot Games/LoL, EA, Epic Games), Azure (Xbox Live, Halo), OVH и Hetzner (EU MMO-серверы, Minecraft). Гео: Европа + Северная Америка.",
        "sort_order": 40,
        "providers": [
            "amazon-ips.txt",
            "azure-ips.txt",
            "ovh-ips.txt",
            "hetzner-ips.txt",
        ],
        "settings": {
            "region_scopes": ["europe", "north-america"],
            "exclude_ru_cidrs": False,
            "include_non_geo_fallback": True,
        },
    },
    {
        "key": "all_cloud",
        "name": "Все облачные провайдеры",
        "description": "AWS, Azure, Google Cloud, DigitalOcean, Hetzner, OVH, Oracle. Максимальное покрытие облачных сервисов.",
        "sort_order": 50,
        "providers": [
            "amazon-ips.txt",
            "azure-ips.txt",
            "google-ips.txt",
            "digitalocean-ips.txt",
            "hetzner-ips.txt",
            "ovh-ips.txt",
            "oracle-ips.txt",
        ],
        "settings": {
            "region_scopes": ["all"],
            "exclude_ru_cidrs": False,
            "include_non_geo_fallback": True,
        },
    },
    {
        "key": "popular_services",
        "name": "Популярные сервисы",
        "description": "Оптимальный набор для массово используемых сервисов: YouTube/Google, GitHub, Twitch, CDN-платформы и популярные облака.",
        "sort_order": 55,
        "providers": [
            "akamai-ips.txt",
            "amazon-ips.txt",
            "azure-ips.txt",
            "cdn77-ips.txt",
            "cloudflare-ips.txt",
            "digitalocean-ips.txt",
            "fastly-ips.txt",
            "google-ips.txt",
            "hetzner-ips.txt",
            "oracle-ips.txt",
            "ovh-ips.txt",
        ],
        "settings": {
            "region_scopes": ["all"],
            "exclude_ru_cidrs": False,
            "include_non_geo_fallback": True,
        },
    },
    {
        "key": "all_providers",
        "name": "Все провайдеры",
        "description": "Полный список всех доступных провайдеров. Максимальное покрытие — автоматически сжимается до 900 маршрутов.",
        "sort_order": 60,
        "providers": [
            "akamai-ips.txt",
            "amazon-ips.txt",
            "azure-ips.txt",
            "cdn77-ips.txt",
            "cloudflare-ips.txt",
            "digitalocean-ips.txt",
            "fastly-ips.txt",
            "google-ips.txt",
            "hetzner-ips.txt",
            "m247-ips.txt",
            "ovh-ips.txt",
            "oracle-ips.txt",
        ],
        "settings": {
            "region_scopes": ["all"],
            "exclude_ru_cidrs": False,
            "include_non_geo_fallback": True,
        },
    },
]
